maxGameLength: 360
username: ""
password: ""
authMethod: None
authToken: ""
realm: eu.actual.battle.net
characterName: WutsKulerDenLit
commandLineArgs: ""
killD2OnStop: true
classicMode: false
closeMiniPanel: false
useCentralizedPickit: false
hidePortraits: true
scheduler:
    enabled: true
    days:
        - dayOfWeek: 0
          timeRange: []
        - dayOfWeek: 1
          timeRange: []
        - dayOfWeek: 2
          timeRange: []
        - dayOfWeek: 3
          timeRange: []
        - dayOfWeek: 4
          timeRange: []
        - dayOfWeek: 5
          timeRange: []
        - dayOfWeek: 6
          timeRange: []
health:
    healingPotionAt: 90
    manaPotionAt: 75
    rejuvPotionAtLife: 50
    rejuvPotionAtMana: 30
    mercHealingPotionAt: 80
    mercRejuvPotionAt: 30
    chickenAt: 25
    mercChickenAt: 10
inventory:
    inventoryLock:
        - - 1
          - 1
          - 1
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
        - - 1
          - 1
          - 1
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
        - - 1
          - 1
          - 1
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
        - - 1
          - 1
          - 1
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
    beltColumns:
        - healing
        - mana
        - rejuvenation
        - rejuvenation
character:
    class: nova
    useMerc: true
    stashToShared: false
    useTeleport: true
    berserker_barb:
        find_item_switch: false
        skip_potion_pickup_in_travincal: false
    nova_sorceress:
        boss_static_threshold: 50
    mosaic_sin:
        useTigerStrike: false
        useCobraStrike: false
        useClawsOfThunder: false
        useBladesOfIce: false
        useFistsOfFire: false
game:
    minGoldPickupThreshold: 500000
    useCainIdentify: true
    clearTPArea: true
    difficulty: hell
    randomizeRuns: false
    runs:
        - summoner
    createLobbyGames: false
    pindleskin:
        skipOnImmunities: []
    cows:
        openChests: false
    pit:
        moveThroughBlackMarsh: false
        openChests: true
        focusOnElitePacks: true
        onlyClearLevel2: false
    andariel:
        clearRoom: false
    stony_tomb:
        openChests: true
        focusOnElitePacks: false
    mausoleum:
        openChests: false
        focusOnElitePacks: false
    ancient_tunnels:
        openChests: false
        focusOnElitePacks: false
    drifter_cavern:
        openChests: true
        focusOnElitePacks: false
    spider_cavern:
        openChests: true
        focusOnElitePacks: false
    arachnid_lair:
        openChests: false
        focusOnElitePacks: false
    mephisto:
        killCouncilMembers: true
        openChests: false
        exitToA4: false
    tristram:
        clearPortal: true
        focusOnElitePacks: false
    nihlathak:
        clearArea: true
    diablo:
        killDiablo: true
        startFromStar: false
        focusOnElitePacks: false
        disableItemPickupDuringBosses: true
        attackFromDistance: 4
    baal:
        killBaal: false
        dollQuit: false
        soulQuit: true
        clearFloors: false
        onlyElites: false
    eldritch:
        killShenk: true
    lowerkurastchests:
        openRacks: true
    terror_zone:
        focusOnElitePacks: false
        skipOnImmunities: []
        skipOtherRuns: false
        areas:
            - 2
            - 3
            - 4
            - 5
            - 6
            - 8
            - 9
            - 10
            - 11
            - 12
            - 14
            - 15
            - 17
            - 18
            - 19
            - 20
            - 29
            - 30
            - 31
            - 32
            - 33
            - 34
            - 35
            - 36
            - 38
            - 39
            - 41
            - 42
            - 43
            - 44
            - 45
            - 47
            - 48
            - 49
            - 56
            - 57
            - 58
            - 60
            - 61
            - 65
            - 66
            - 74
            - 76
            - 77
            - 78
            - 80
            - 83
            - 85
            - 88
            - 89
            - 91
            - 94
            - 95
            - 100
            - 104
            - 105
            - 106
            - 107
            - 108
            - 110
            - 111
            - 112
            - 113
            - 114
            - 115
            - 116
            - 118
            - 119
            - 121
            - 125
            - 126
            - 128
        openChests: false
    leveling:
        ensurePointsAllocation: false
        ensureKeyBinding: false
    quests:
        clearDen: false
        rescueCain: false
        retrieveHammer: false
        getCube: false
        killRadament: false
        retrieveBook: false
        killIzual: false
        killShenk: false
        rescueAnya: false
        killAncients: false
    summoner:
        clearArea: false
        clearGhosts: true
companion:
    leader: false
    leaderName: ""
    gameNameTemplate: game-
    gamePassword: xxx
gambling:
    enabled: true
    items:
        - coronet
        - amulet
        - ring
cubing:
    enabled: true
    enabledRecipes:
        - Perfect Amethyst
        - Perfect Diamond
        - Perfect Emerald
        - Perfect Ruby
        - Perfect Sapphire
        - Perfect Topaz
        - Perfect Skull
        - Upgrade El
        - Upgrade Eld
        - Upgrade Tir
        - Upgrade Nef
        - Upgrade Eth
        - Upgrade Ith
        - Upgrade Tal
        - Upgrade Ral
        - Upgrade Ort
        - Upgrade Thul
        - Upgrade Amn
        - Upgrade Sol
        - Upgrade Shael
        - Upgrade Dol
        - Upgrade Io
        - Upgrade Lum
        - Upgrade Ko
        - Upgrade Fal
        - Upgrade Lem
        - Upgrade Pul
        - Upgrade Um
        - Upgrade Mal
        - Upgrade Gul
        - Reroll GrandCharms
        - Caster Amulet
    skipPerfectAmethysts: true
    skipPerfectRubies: false
backtotown:
    noHpPotions: true
    noMpPotions: false
    mercDied: true
    equipmentBroken: false
